### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by randomunknwn** [Hacker-Data/Thanos-Ransomware-Builder#1]
Hi, when I run the builder it says its not licensed for that machine.. is there any way I can contact you?

i-muknown at protonmail dotcom

cheers

**Comment by Hacker-Data** [comment]
You Need to Get Program License To Activate This Builder Program

**Comment by randomunknwn** [comment]
finally managed to contact you, so happy.

how much is the license?

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Hacker-Data** [comment]
$200 Lifetime

**Comment by randomunknwn** [comment]
sounds good, just msgd you

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Hacker-Data** [comment]
Contact Telegram @Hacker_Data

**Comment by Hacker-Data** [comment]
> Hi, when I run the builder it says its not licensed for that machine.. is there any way I can contact you?
> 
> i-muknown at protonmail dotcom
> 
> cheers

Contact Telegram @Hacker_Data
